version: '3.9'

services:
  api:
    container_name: nestjs-graphql
    build: .
    ports: 
      - 3000:3000
      
  database:
    container_name: nestjs-db
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432